### ISSUE TITLE
Unhandled exception when trying to dump a medium with my DVD drive.

### ISSUE THREAD

**Issue by maxz** [claunia/DiscImageChef#842]
### Version

5.3.0

### Tested debug version?

- [X] Yes

### Which operating systems have you used?

- [ ] Windows
- [X] Linux
- [ ] macOS
- [ ] Other

### What is the architectural bit size you're using?

- [ ] 32-bit
- [X] 64-bit
- [ ] Unsure or unknown

### What processor are you using?

- [X] An Intel or AMD
- [ ] An ARM or Apple Silicon
- [ ] Unsure or unknown

### Device manufacturer

Hitachi - LG Data Storage, Inc. (reported as MediaTek Inc. by `lsusb`)

### Device model

Slim Portable DVD Writer GP60NB60

### Bus the device uses to attach to the computer

- [ ] Parallel ATA
- [ ] Serial ATA
- [ ] SCSI (any)
- [ ] ATAPI (mark above if parallel or serial)
- [X] USB
- [ ] FireWire
- [ ] PCMCIA
- [ ] SecureDigital
- [ ] MultiMediaCard

### USB cable or card reader manufacturer

SHENZHEN DONG TIAN TONG LI ELECTRICITY CO LTD (Original device cable.)

### USB cable or card reader model

28AWG/1P+24AWGX2C (Original device cable.)

### What were you doing when it failed?

- [X] I was dumping media (disk, tape, etc)...
- [ ] I was retrieving media (disk, tape, etc) information...
- [ ] I was scanning media (disk, tape, etc)...
- [ ] I was retrieving device information...

### Description

Aaru crashes when trying to dump a CD-ROM, DVD-ROM-5 or DVD-ROM-9 with my USB DVD drive.

### Exact command line used

`DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 ./aaru media dump --encoding UTF-8 --format 'Aaru Format' --metadata --speed 0 --private --verbose --debug /dev/sr0 /tmp/BUG`

### Expected behavior

Aaru should have read and dumped the disc, providing me with an `.aaruf` file, a `.cicm.xml` and various other metadata files which are of less importance to me.

At the very least it should have failed in a controlled way.

### Actual behavior

Aaru crashed due to an unhandled exception.

### Output of command execution with debug output enabled

```shell
aaru 5.3.2+f4fef21d
Copyright © 2011-2023 Natalia Portillo

DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=/dev/sr0
DEBUG (Dump-Media command): --encoding=UTF-8
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --fix-offset=True
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --format=Aaru Format
DEBUG (Dump-Media command): --metadata=True
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --output=/tmp/BUG
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --trim=True
DEBUG (Dump-Media command): --verbose=True
DEBUG (Dump-Media command): --subchannel=any
DEBUG (Dump-Media command): --private=True
DEBUG (Dump-Media command): --fix-subchannel-position=True
DEBUG (Dump-Media command): --retry-subchannel=True
DEBUG (Dump-Media command): --fix-subchannel=False
DEBUG (Dump-Media command): --fix-subchannel-crc=False
DEBUG (Dump-Media command): --generate-subchannels=False
DEBUG (Dump-Media command): --skip-cdiready-hole=True
DEBUG (Dump-Media command): --eject=False
DEBUG (Dump-Media command): --max-blocks=64
DEBUG (Dump-Media command): --use-buffered-reads=True
DEBUG (Dump-Media command): --store-encrypted=True
DEBUG (Dump-Media command): --title-keys=True
DEBUG (Dump-Media command): Parsed options:
Using encoding for Unicode (UTF-8).
DEBUG (SCSI Device): INQUIRY took 0.8436 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 0.006 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: False, Last Error: 0) took 2 ms.
Output image format: Aaru Format (49360069-1784-4a2f-b723-0c844d610b0a).
Device not in database, please create a device report and attach it to a Github issue.             
DEBUG (SCSI Device): TEST UNIT READY took 2 ms.

DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: False, Last Error: 0) took 3 ms.
DEBUG (SCSI Device): MODE SENSE(6) took 4 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Aaru.Decoders.SCSI.Modes.DecodeModeHeader6(Byte[] modeResponse, PeripheralDeviceTypes deviceType) in /home/claunia/Development/Aaru/Aaru/Aaru.Decoders/SCSI/Modes/Mode6.cs:line 67
   at Aaru.Decoders.SCSI.Modes.DecodeMode6(Byte[] modeResponse, PeripheralDeviceTypes deviceType) in /home/claunia/Development/Aaru/Aaru/Aaru.Decoders/SCSI/Modes/Mode6.cs:line 107
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/MMC.cs:line 222
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 238
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 248
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys) in /home/claunia/Development/Aaru/Aaru/Aaru/Commands/Media/Dump.cs:line 679
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### Media details

Happens with any CD-ROM, DVD-ROM-5 or DVD-ROM-9 I tried.

**Comment by maxz** [comment]
Since I tested something with `6.0.0~alpha9+e10c237e` for my other report I also tested this against alpha9 and it still exists there in the same way.

**Comment by claunia** [comment]
Can you try with 5aa21b65b81cc5c0e30d918ffd448cff1c5d355c ? We just fixed a similar crash with another device in Windows and may have fixed this issue as well.

**Comment by maxz** [comment]
I tried `6.0.0~alpha9+97827d9b.97827d9bfe0750dbcb028416ef4cd80b26c4fb60` and it still fails at the same function calls.

```
aaru 6.0.0~alpha9+97827d9b.97827d9bfe0750dbcb028416ef4cd80b26c4fb60
Copyright © 2011-2023 Natalia Portillo

DEBUG (Dump-Media command): --cicm-xml=
DEBUG (Dump-Media command): --debug=True
DEBUG (Dump-Media command): --device=/dev/sr0
DEBUG (Dump-Media command): --encoding=UTF-8
DEBUG (Dump-Media command): --first-pregap=False
DEBUG (Dump-Media command): --fix-offset=True
DEBUG (Dump-Media command): --force=False
DEBUG (Dump-Media command): --format=Aaru Format
DEBUG (Dump-Media command): --metadata=True
DEBUG (Dump-Media command): --options=
DEBUG (Dump-Media command): --output=/tmp/BUG
DEBUG (Dump-Media command): --persistent=False
DEBUG (Dump-Media command): --resume=True
DEBUG (Dump-Media command): --retry-passes=5
DEBUG (Dump-Media command): --skip=512
DEBUG (Dump-Media command): --stop-on-error=False
DEBUG (Dump-Media command): --trim=True
DEBUG (Dump-Media command): --verbose=True
DEBUG (Dump-Media command): --subchannel=any
DEBUG (Dump-Media command): ----private=True
DEBUG (Dump-Media command): --fix-subchannel-position=True
DEBUG (Dump-Media command): --retry-subchannel=True
DEBUG (Dump-Media command): --fix-subchannel=False
DEBUG (Dump-Media command): --fix-subchannel-crc=False
DEBUG (Dump-Media command): --generate-subchannels=False
DEBUG (Dump-Media command): --skip-cdiready-hole=True
DEBUG (Dump-Media command): --eject=False
DEBUG (Dump-Media command): --max-blocks=64
DEBUG (Dump-Media command): --use-buffered-reads=True
DEBUG (Dump-Media command): --store-encrypted=True
DEBUG (Dump-Media command): --title-keys=True
DEBUG (Dump-Media command): --ignore-cdr-runouts=10
DEBUG (Dump-Media command): --create-graph=True
DEBUG (Dump-Media command): --dimensions=1080
DEBUG (Dump-Media command): --aaru-metadata=
DEBUG (Dump-Media command): Parsed options:
DEBUG (SCSI Device): INQUIRY took 1 ms.
DEBUG (SCSI Device): INQUIRY took 1 ms.
DEBUG (ATA Device): IDENTIFY PACKET DEVICE took 0.0051 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 264, Return Type: Single, Sense: 
False, Last Error: 0) took 1 ms.
Device not in database, please create a device report and attach it to a Github issue.
DEBUG (SCSI Device): TEST UNIT READY took 3 ms.
DEBUG (SCSI Device): GET CONFIGURATION (Starting Feature Number: 0, Return Type: Current, Sense: 
False, Last Error: 0) took 4 ms.
DEBUG (SCSI Device): MODE SENSE(6) took 2 ms.
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Aaru.Decoders.SCSI.Modes.DecodeModeHeader6(Byte[] modeResponse, PeripheralDeviceTypes deviceType) in /[REDACTED]/Aaru/Aaru.Decoders/SCSI/Modes/Mode6.cs:line 66
   at Aaru.Decoders.SCSI.Modes.DecodeMode6(Byte[] modeResponse, PeripheralDeviceTypes deviceType) in /[REDACTED]/Aaru/Aaru.Decoders/SCSI/Modes/Mode6.cs:line 106
   at Aaru.Core.Devices.Dumping.Dump.Mmc() in /[REDACTED]/Aaru/Aaru.Core/Devices/Dumping/MMC.cs:line 219
   at Aaru.Core.Devices.Dumping.Dump.Scsi() in /[REDACTED]/Aaru/Aaru.Core/Devices/Dumping/SCSI.cs:line 252
   at Aaru.Core.Devices.Dumping.Dump.Start() in /[REDACTED]/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 282
   at Aaru.Commands.Media.DumpMediaCommand.<>c__DisplayClass4_3.<Invoke>b__12(ProgressContext ctx) in /[REDACTED]/Aaru/Aaru/Commands/Media/Dump.cs:line 760
   at Spectre.Console.Progress.<>c__DisplayClass25_0.<Start>b__0(ProgressContext ctx) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 65
   at Spectre.Console.Progress.<>c__DisplayClass27_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 98
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Progress.StartAsync(Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 96
   at Spectre.Console.Progress.Start(Action`1 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 69
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys, UInt32 ignoreCdrRunOuts, Boolean createGraph, UInt32 dimensions, String aaruMetadata) in /[REDACTED]/Aaru/Aaru/Commands/Media/Dump.cs:line 693
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by claunia** [comment]
Please paste the output of `sg_modes -6 -H /dev/sr0` and `sg_modes -H /dev/sr0`

**Comment by maxz** [comment]
MODE SENSE(6):
```
    HL-DT-ST  DVDRAM GP60NB60   RF02   peripheral_type: cd/dvd [0x5]
Invalid block descriptor length=8, ignore
 00     09 70 00 08 00 00 00 00  00 00
```

MODE SENSE(10):
```
    HL-DT-ST  DVDRAM GP60NB60   RF02   peripheral_type: cd/dvd [0x5]
 00     01 08 70 00 00 00 00 00  01 0a 80 c0 00 00 00 00
 10     00 00 00 00 05 32 41 c4  08 00 00 00 00 00 00 00
 20     00 00 00 96 00 00 00 00  00 00 00 00 00 00 00 00
 30     00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
 40     00 00 00 00 00 00 00 00  08 0a 04 00 00 00 00 00
 50     00 00 00 00 0d 06 00 00  00 3c 00 4b 0e 0e 04 00
 60     00 00 00 4b 01 d8 02 d8  00 00 00 00 18 1a 00 01
 70     00 01 00 00 00 00 00 01  00 01 00 00 00 00 00 00
 80     00 00 00 01 00 01 00 00  1a 0a 00 03 00 00 00 64
 90     00 00 01 40 9c 0a 00 04  00 00 02 58 00 00 00 00
 a0     1d 08 00 00 00 00 00 06  04 b0 20 0a 00 00 00 00
 b0     00 00 00 00 00 00 2a 42  3f 37 f1 77 29 23 10 8a
 c0     01 00 03 00 10 8a 00 10  10 8a 10 8a 00 01 00 00
 d0     00 00 10 8a 00 03 00 00  10 8a 00 00 0b 06 00 00
 e0     06 e4 00 00 00 00 00 00  00 00 00 00 00 00 00 00
 f0     00 00 00 00 00 00 00 00  00 00 30 0e 11 11 00 00
 100    00 00 00 00 00 00 00 00  00 00
```

**Comment by maxz** [comment]
I tested version `6.0.0~alpha9+5448b77e.5448b77ea8315c4857e7128903baa5c899224719` and it works as expected.

**Comment by claunia** [comment]
Neat. Happy preservation!
